[package]
name = "alatus-gui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
alatus-core = { path = "../alatus-core" }
alatus-ipc = { path = "../alatus-ipc" }
alatus-profile = { path = "../alatus-profile" }
futures-util = "0.3"
slint = "1.9"
tokio = { version = "1.38", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zbus = { version = "4.4", default-features = false, features = ["tokio"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
slint-build = "1.9"
