[package]
name = "alatus-drivers"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
alatus-core = { path = "../alatus-core" }
async-trait = "0.1"
tokio = { version = "1.38", features = ["fs", "io-util", "sync", "rt"] }
tracing = "0.1"

[dev-dependencies]
tempfile = "3.10"
tokio = { version = "1.38", features = ["macros", "rt-multi-thread"] }
