# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_alatus_global_optspecs
    string join \n h/help V/version
end

function __fish_alatus_needs_command
    # Figure out if the current invocation already has a command.
    set -l cmd (commandline -opc)
    set -e cmd[1]
    argparse -s (__fish_alatus_global_optspecs) -- $cmd 2>/dev/null
    or return
    if set -q argv[1]
        # Also print the command, so this can be used to figure out what it is.
        echo $argv[1]
        return 1
    end
    return 0
end

function __fish_alatus_using_subcommand
    set -l cmd (__fish_alatus_needs_command)
    test -z "$cmd"
    and return 1
    contains -- $cmd[1] $argv
end

complete -c alatus -n "__fish_alatus_needs_command" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_needs_command" -s V -l version -d 'Print version'
complete -c alatus -n "__fish_alatus_needs_command" -f -a "status" -d 'Show system, firmware, battery, and lighting status'
complete -c alatus -n "__fish_alatus_needs_command" -f -a "watch" -d 'Stream live JSON status line-by-line (alias for \'alatus status -j -w\')'
complete -c alatus -n "__fish_alatus_needs_command" -f -a "monitor" -d 'Live real-time hardware telemetry monitor'
complete -c alatus -n "__fish_alatus_needs_command" -f -a "mode" -d 'Query or set firmware power/fan mode'
complete -c alatus -n "__fish_alatus_needs_command" -f -a "fan" -d 'Query or set fan profile'
complete -c alatus -n "__fish_alatus_needs_command" -f -a "cycle" -d 'Cycle through thermal profiles: Quiet -> Balanced -> Performance -> Full -> Quiet'
complete -c alatus -n "__fish_alatus_needs_command" -f -a "quiet" -d 'Shortcut: Switch directly to Quiet thermal profile'
complete -c alatus -n "__fish_alatus_needs_command" -f -a "balanced" -d 'Shortcut: Switch directly to Balanced thermal profile'
complete -c alatus -n "__fish_alatus_needs_command" -f -a "perf" -d 'Shortcut: Switch directly to Performance thermal profile'
complete -c alatus -n "__fish_alatus_needs_command" -f -a "full" -d 'Shortcut: Switch directly to Full speed thermal profile'
complete -c alatus -n "__fish_alatus_needs_command" -f -a "oled" -d 'OLED panel care, cumulative usage hours, idle dimming, and pixel refresh'
complete -c alatus -n "__fish_alatus_needs_command" -f -a "display" -d 'Display panel resolution, refresh rate switching, and auto power-matching'
complete -c alatus -n "__fish_alatus_needs_command" -f -a "charge-limit" -d 'Set battery charge limit threshold (0-100%)'
complete -c alatus -n "__fish_alatus_needs_command" -f -a "rgb" -d 'Control keyboard RGB backlight and desktop accent color sync'
complete -c alatus -n "__fish_alatus_needs_command" -f -a "daemon" -d 'Manage system hardware daemon and user desktop session background services'
complete -c alatus -n "__fish_alatus_needs_command" -f -a "completions" -d 'Generate shell auto-completion scripts for Bash, Zsh, or Fish'
complete -c alatus -n "__fish_alatus_needs_command" -f -a "session" -d 'Run desktop session integration agent (hidden/legacy compatibility)'
complete -c alatus -n "__fish_alatus_needs_command" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c alatus -n "__fish_alatus_using_subcommand status" -s j -l json -d 'Output status formatted as JSON for scripting and Waybar integration'
complete -c alatus -n "__fish_alatus_using_subcommand status" -s w -l watch -d 'Stream live JSON status line-by-line on events / ticker (ideal for Waybar)'
complete -c alatus -n "__fish_alatus_using_subcommand status" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand watch" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand monitor" -s i -l interval-ms -d 'Polling interval in milliseconds' -r
complete -c alatus -n "__fish_alatus_using_subcommand monitor" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and not __fish_seen_subcommand_from get set balanced quiet performance full cycle auto help" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and not __fish_seen_subcommand_from get set balanced quiet performance full cycle auto help" -f -a "get" -d 'Get current firmware mode'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and not __fish_seen_subcommand_from get set balanced quiet performance full cycle auto help" -f -a "set" -d 'Set firmware mode (balanced, quiet, performance, full)'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and not __fish_seen_subcommand_from get set balanced quiet performance full cycle auto help" -f -a "balanced" -d 'Switch to Balanced profile'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and not __fish_seen_subcommand_from get set balanced quiet performance full cycle auto help" -f -a "quiet" -d 'Switch to Quiet profile'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and not __fish_seen_subcommand_from get set balanced quiet performance full cycle auto help" -f -a "performance" -d 'Switch to Performance profile'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and not __fish_seen_subcommand_from get set balanced quiet performance full cycle auto help" -f -a "full" -d 'Switch to Full speed profile'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and not __fish_seen_subcommand_from get set balanced quiet performance full cycle auto help" -f -a "cycle" -d 'Cycle through profiles: Quiet -> Balanced -> Performance -> Full -> Quiet'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and not __fish_seen_subcommand_from get set balanced quiet performance full cycle auto help" -f -a "auto" -d 'Query or configure auto-switching thermal profile on power changes'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and not __fish_seen_subcommand_from get set balanced quiet performance full cycle auto help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and __fish_seen_subcommand_from set" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and __fish_seen_subcommand_from balanced" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and __fish_seen_subcommand_from quiet" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and __fish_seen_subcommand_from performance" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and __fish_seen_subcommand_from full" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and __fish_seen_subcommand_from cycle" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and __fish_seen_subcommand_from auto" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and __fish_seen_subcommand_from help" -f -a "get" -d 'Get current firmware mode'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and __fish_seen_subcommand_from help" -f -a "set" -d 'Set firmware mode (balanced, quiet, performance, full)'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and __fish_seen_subcommand_from help" -f -a "balanced" -d 'Switch to Balanced profile'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and __fish_seen_subcommand_from help" -f -a "quiet" -d 'Switch to Quiet profile'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and __fish_seen_subcommand_from help" -f -a "performance" -d 'Switch to Performance profile'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and __fish_seen_subcommand_from help" -f -a "full" -d 'Switch to Full speed profile'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and __fish_seen_subcommand_from help" -f -a "cycle" -d 'Cycle through profiles: Quiet -> Balanced -> Performance -> Full -> Quiet'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and __fish_seen_subcommand_from help" -f -a "auto" -d 'Query or configure auto-switching thermal profile on power changes'
complete -c alatus -n "__fish_alatus_using_subcommand mode; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and not __fish_seen_subcommand_from get set balanced quiet performance full cycle help" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and not __fish_seen_subcommand_from get set balanced quiet performance full cycle help" -f -a "get" -d 'Get current fan profile'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and not __fish_seen_subcommand_from get set balanced quiet performance full cycle help" -f -a "set" -d 'Set fan profile (balanced, quiet, performance, full)'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and not __fish_seen_subcommand_from get set balanced quiet performance full cycle help" -f -a "balanced" -d 'Switch to Balanced profile'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and not __fish_seen_subcommand_from get set balanced quiet performance full cycle help" -f -a "quiet" -d 'Switch to Quiet profile'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and not __fish_seen_subcommand_from get set balanced quiet performance full cycle help" -f -a "performance" -d 'Switch to Performance profile'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and not __fish_seen_subcommand_from get set balanced quiet performance full cycle help" -f -a "full" -d 'Switch to Full speed profile'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and not __fish_seen_subcommand_from get set balanced quiet performance full cycle help" -f -a "cycle" -d 'Cycle through fan profiles: Quiet -> Balanced -> Performance -> Full -> Quiet'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and not __fish_seen_subcommand_from get set balanced quiet performance full cycle help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and __fish_seen_subcommand_from set" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and __fish_seen_subcommand_from balanced" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and __fish_seen_subcommand_from quiet" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and __fish_seen_subcommand_from performance" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and __fish_seen_subcommand_from full" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and __fish_seen_subcommand_from cycle" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and __fish_seen_subcommand_from help" -f -a "get" -d 'Get current fan profile'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and __fish_seen_subcommand_from help" -f -a "set" -d 'Set fan profile (balanced, quiet, performance, full)'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and __fish_seen_subcommand_from help" -f -a "balanced" -d 'Switch to Balanced profile'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and __fish_seen_subcommand_from help" -f -a "quiet" -d 'Switch to Quiet profile'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and __fish_seen_subcommand_from help" -f -a "performance" -d 'Switch to Performance profile'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and __fish_seen_subcommand_from help" -f -a "full" -d 'Switch to Full speed profile'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and __fish_seen_subcommand_from help" -f -a "cycle" -d 'Cycle through fan profiles: Quiet -> Balanced -> Performance -> Full -> Quiet'
complete -c alatus -n "__fish_alatus_using_subcommand fan; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c alatus -n "__fish_alatus_using_subcommand cycle" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand quiet" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand balanced" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand perf" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand full" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand oled; and not __fish_seen_subcommand_from status dim refresh help" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand oled; and not __fish_seen_subcommand_from status dim refresh help" -f -a "status" -d 'Show OLED care status, cumulative panel hours, cycle counts, and idle dimming state'
complete -c alatus -n "__fish_alatus_using_subcommand oled; and not __fish_seen_subcommand_from status dim refresh help" -f -a "dim" -d 'Toggle OLED idle dimming or specify target dimming percentage level'
complete -c alatus -n "__fish_alatus_using_subcommand oled; and not __fish_seen_subcommand_from status dim refresh help" -f -a "refresh" -d 'Trigger an immediate OLED pixel refresh conditioning cycle'
complete -c alatus -n "__fish_alatus_using_subcommand oled; and not __fish_seen_subcommand_from status dim refresh help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c alatus -n "__fish_alatus_using_subcommand oled; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand oled; and __fish_seen_subcommand_from dim" -l dim -d 'Alternative flag to enable or disable idle dimming' -r
complete -c alatus -n "__fish_alatus_using_subcommand oled; and __fish_seen_subcommand_from dim" -l level -d 'Target dimming percentage level (10-100)' -r
complete -c alatus -n "__fish_alatus_using_subcommand oled; and __fish_seen_subcommand_from dim" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand oled; and __fish_seen_subcommand_from refresh" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand oled; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show OLED care status, cumulative panel hours, cycle counts, and idle dimming state'
complete -c alatus -n "__fish_alatus_using_subcommand oled; and __fish_seen_subcommand_from help" -f -a "dim" -d 'Toggle OLED idle dimming or specify target dimming percentage level'
complete -c alatus -n "__fish_alatus_using_subcommand oled; and __fish_seen_subcommand_from help" -f -a "refresh" -d 'Trigger an immediate OLED pixel refresh conditioning cycle'
complete -c alatus -n "__fish_alatus_using_subcommand oled; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c alatus -n "__fish_alatus_using_subcommand display; and not __fish_seen_subcommand_from status rate dim help" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand display; and not __fish_seen_subcommand_from status rate dim help" -f -a "status" -d 'Show active panel connector, current refresh rate, resolution, and auto-refresh state'
complete -c alatus -n "__fish_alatus_using_subcommand display; and not __fish_seen_subcommand_from status rate dim help" -f -a "rate" -d 'Switch refresh rate in Hz (e.g. 60, 120) or toggle auto power-matching (auto [on|off])'
complete -c alatus -n "__fish_alatus_using_subcommand display; and not __fish_seen_subcommand_from status rate dim help" -f -a "dim" -d 'Scale flicker-free luminance level at compositor level (10-100%)'
complete -c alatus -n "__fish_alatus_using_subcommand display; and not __fish_seen_subcommand_from status rate dim help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c alatus -n "__fish_alatus_using_subcommand display; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand display; and __fish_seen_subcommand_from rate" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand display; and __fish_seen_subcommand_from dim" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand display; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show active panel connector, current refresh rate, resolution, and auto-refresh state'
complete -c alatus -n "__fish_alatus_using_subcommand display; and __fish_seen_subcommand_from help" -f -a "rate" -d 'Switch refresh rate in Hz (e.g. 60, 120) or toggle auto power-matching (auto [on|off])'
complete -c alatus -n "__fish_alatus_using_subcommand display; and __fish_seen_subcommand_from help" -f -a "dim" -d 'Scale flicker-free luminance level at compositor level (10-100%)'
complete -c alatus -n "__fish_alatus_using_subcommand display; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c alatus -n "__fish_alatus_using_subcommand charge-limit" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and not __fish_seen_subcommand_from status set-color set-brightness off on sync help" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and not __fish_seen_subcommand_from status set-color set-brightness off on sync help" -f -a "status" -d 'Show current RGB status'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and not __fish_seen_subcommand_from status set-color set-brightness off on sync help" -f -a "set-color" -d 'Set static RGB color via HEX (#RRGGBB, RRGGBB) or RGB values (R,G,B)'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and not __fish_seen_subcommand_from status set-color set-brightness off on sync help" -f -a "set-brightness" -d 'Set RGB brightness level (0-100% or 0-3)'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and not __fish_seen_subcommand_from status set-color set-brightness off on sync help" -f -a "off" -d 'Turn off keyboard RGB backlight'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and not __fish_seen_subcommand_from status set-color set-brightness off on sync help" -f -a "on" -d 'Turn on keyboard RGB backlight'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and not __fish_seen_subcommand_from status set-color set-brightness off on sync help" -f -a "sync" -d 'Toggle desktop accent color synchronization with keyboard backlighting'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and not __fish_seen_subcommand_from status set-color set-brightness off on sync help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and __fish_seen_subcommand_from set-color" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and __fish_seen_subcommand_from set-brightness" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and __fish_seen_subcommand_from off" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and __fish_seen_subcommand_from on" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and __fish_seen_subcommand_from sync" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show current RGB status'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and __fish_seen_subcommand_from help" -f -a "set-color" -d 'Set static RGB color via HEX (#RRGGBB, RRGGBB) or RGB values (R,G,B)'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and __fish_seen_subcommand_from help" -f -a "set-brightness" -d 'Set RGB brightness level (0-100% or 0-3)'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and __fish_seen_subcommand_from help" -f -a "off" -d 'Turn off keyboard RGB backlight'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and __fish_seen_subcommand_from help" -f -a "on" -d 'Turn on keyboard RGB backlight'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and __fish_seen_subcommand_from help" -f -a "sync" -d 'Toggle desktop accent color synchronization with keyboard backlighting'
complete -c alatus -n "__fish_alatus_using_subcommand rgb; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and not __fish_seen_subcommand_from session system status help" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and not __fish_seen_subcommand_from session system status help" -f -a "session" -d 'Manage the desktop session background agent (alatus-session.service)'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and not __fish_seen_subcommand_from session system status help" -f -a "system" -d 'Manage the system hardware daemon (alatusd.service)'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and not __fish_seen_subcommand_from session system status help" -f -a "status" -d 'Show status of both background daemons'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and not __fish_seen_subcommand_from session system status help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and __fish_seen_subcommand_from session" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and __fish_seen_subcommand_from session" -f -a "start" -d 'Start the service'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and __fish_seen_subcommand_from session" -f -a "stop" -d 'Stop the service'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and __fish_seen_subcommand_from session" -f -a "restart" -d 'Restart the service'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and __fish_seen_subcommand_from session" -f -a "status" -d 'Query service status'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and __fish_seen_subcommand_from session" -f -a "run" -d 'Run the daemon in foreground (used by systemd user unit)'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and __fish_seen_subcommand_from session" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and __fish_seen_subcommand_from system" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and __fish_seen_subcommand_from system" -f -a "start" -d 'Start the service'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and __fish_seen_subcommand_from system" -f -a "stop" -d 'Stop the service'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and __fish_seen_subcommand_from system" -f -a "restart" -d 'Restart the service'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and __fish_seen_subcommand_from system" -f -a "status" -d 'Query service status'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and __fish_seen_subcommand_from system" -f -a "run" -d 'Run the daemon in foreground (used by systemd user unit)'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and __fish_seen_subcommand_from system" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and __fish_seen_subcommand_from help" -f -a "session" -d 'Manage the desktop session background agent (alatus-session.service)'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and __fish_seen_subcommand_from help" -f -a "system" -d 'Manage the system hardware daemon (alatusd.service)'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show status of both background daemons'
complete -c alatus -n "__fish_alatus_using_subcommand daemon; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c alatus -n "__fish_alatus_using_subcommand completions" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand session; and not __fish_seen_subcommand_from status set pixel-refresh help" -l sync-accent -d 'Enable XDG desktop accent color sync (default: true)'
complete -c alatus -n "__fish_alatus_using_subcommand session; and not __fish_seen_subcommand_from status set pixel-refresh help" -l no-accent -d 'Disable XDG desktop accent color sync'
complete -c alatus -n "__fish_alatus_using_subcommand session; and not __fish_seen_subcommand_from status set pixel-refresh help" -l auto-refresh -d 'Enable auto display panel refresh rate switching (default: true)'
complete -c alatus -n "__fish_alatus_using_subcommand session; and not __fish_seen_subcommand_from status set pixel-refresh help" -l no-refresh -d 'Disable auto display panel refresh rate switching'
complete -c alatus -n "__fish_alatus_using_subcommand session; and not __fish_seen_subcommand_from status set pixel-refresh help" -l oled-care -d 'Enable OLED Care and idle dimming (default: true)'
complete -c alatus -n "__fish_alatus_using_subcommand session; and not __fish_seen_subcommand_from status set pixel-refresh help" -l no-oled-care -d 'Disable OLED Care and idle dimming'
complete -c alatus -n "__fish_alatus_using_subcommand session; and not __fish_seen_subcommand_from status set pixel-refresh help" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand session; and not __fish_seen_subcommand_from status set pixel-refresh help" -f -a "status" -d 'Show active session agent status and configuration'
complete -c alatus -n "__fish_alatus_using_subcommand session; and not __fish_seen_subcommand_from status set pixel-refresh help" -f -a "set" -d 'Dynamically configure session subsystems on the running agent'
complete -c alatus -n "__fish_alatus_using_subcommand session; and not __fish_seen_subcommand_from status set pixel-refresh help" -f -a "pixel-refresh" -d 'Trigger an immediate OLED pixel refresh conditioning cycle'
complete -c alatus -n "__fish_alatus_using_subcommand session; and not __fish_seen_subcommand_from status set pixel-refresh help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c alatus -n "__fish_alatus_using_subcommand session; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand session; and __fish_seen_subcommand_from set" -l accent -d 'Configure accent color sync (on/off, true/false)' -r
complete -c alatus -n "__fish_alatus_using_subcommand session; and __fish_seen_subcommand_from set" -l refresh -d 'Configure auto panel refresh rate switching (on/off, true/false)' -r
complete -c alatus -n "__fish_alatus_using_subcommand session; and __fish_seen_subcommand_from set" -l oled-care -d 'Configure OLED Care and idle dimming (on/off, true/false)' -r
complete -c alatus -n "__fish_alatus_using_subcommand session; and __fish_seen_subcommand_from set" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand session; and __fish_seen_subcommand_from pixel-refresh" -s h -l help -d 'Print help'
complete -c alatus -n "__fish_alatus_using_subcommand session; and __fish_seen_subcommand_from help" -f -a "status" -d 'Show active session agent status and configuration'
complete -c alatus -n "__fish_alatus_using_subcommand session; and __fish_seen_subcommand_from help" -f -a "set" -d 'Dynamically configure session subsystems on the running agent'
complete -c alatus -n "__fish_alatus_using_subcommand session; and __fish_seen_subcommand_from help" -f -a "pixel-refresh" -d 'Trigger an immediate OLED pixel refresh conditioning cycle'
complete -c alatus -n "__fish_alatus_using_subcommand session; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c alatus -n "__fish_alatus_using_subcommand help; and not __fish_seen_subcommand_from status watch monitor mode fan cycle quiet balanced perf full oled display charge-limit rgb daemon completions session help" -f -a "status" -d 'Show system, firmware, battery, and lighting status'
complete -c alatus -n "__fish_alatus_using_subcommand help; and not __fish_seen_subcommand_from status watch monitor mode fan cycle quiet balanced perf full oled display charge-limit rgb daemon completions session help" -f -a "watch" -d 'Stream live JSON status line-by-line (alias for \'alatus status -j -w\')'
complete -c alatus -n "__fish_alatus_using_subcommand help; and not __fish_seen_subcommand_from status watch monitor mode fan cycle quiet balanced perf full oled display charge-limit rgb daemon completions session help" -f -a "monitor" -d 'Live real-time hardware telemetry monitor'
complete -c alatus -n "__fish_alatus_using_subcommand help; and not __fish_seen_subcommand_from status watch monitor mode fan cycle quiet balanced perf full oled display charge-limit rgb daemon completions session help" -f -a "mode" -d 'Query or set firmware power/fan mode'
complete -c alatus -n "__fish_alatus_using_subcommand help; and not __fish_seen_subcommand_from status watch monitor mode fan cycle quiet balanced perf full oled display charge-limit rgb daemon completions session help" -f -a "fan" -d 'Query or set fan profile'
complete -c alatus -n "__fish_alatus_using_subcommand help; and not __fish_seen_subcommand_from status watch monitor mode fan cycle quiet balanced perf full oled display charge-limit rgb daemon completions session help" -f -a "cycle" -d 'Cycle through thermal profiles: Quiet -> Balanced -> Performance -> Full -> Quiet'
complete -c alatus -n "__fish_alatus_using_subcommand help; and not __fish_seen_subcommand_from status watch monitor mode fan cycle quiet balanced perf full oled display charge-limit rgb daemon completions session help" -f -a "quiet" -d 'Shortcut: Switch directly to Quiet thermal profile'
complete -c alatus -n "__fish_alatus_using_subcommand help; and not __fish_seen_subcommand_from status watch monitor mode fan cycle quiet balanced perf full oled display charge-limit rgb daemon completions session help" -f -a "balanced" -d 'Shortcut: Switch directly to Balanced thermal profile'
complete -c alatus -n "__fish_alatus_using_subcommand help; and not __fish_seen_subcommand_from status watch monitor mode fan cycle quiet balanced perf full oled display charge-limit rgb daemon completions session help" -f -a "perf" -d 'Shortcut: Switch directly to Performance thermal profile'
complete -c alatus -n "__fish_alatus_using_subcommand help; and not __fish_seen_subcommand_from status watch monitor mode fan cycle quiet balanced perf full oled display charge-limit rgb daemon completions session help" -f -a "full" -d 'Shortcut: Switch directly to Full speed thermal profile'
complete -c alatus -n "__fish_alatus_using_subcommand help; and not __fish_seen_subcommand_from status watch monitor mode fan cycle quiet balanced perf full oled display charge-limit rgb daemon completions session help" -f -a "oled" -d 'OLED panel care, cumulative usage hours, idle dimming, and pixel refresh'
complete -c alatus -n "__fish_alatus_using_subcommand help; and not __fish_seen_subcommand_from status watch monitor mode fan cycle quiet balanced perf full oled display charge-limit rgb daemon completions session help" -f -a "display" -d 'Display panel resolution, refresh rate switching, and auto power-matching'
complete -c alatus -n "__fish_alatus_using_subcommand help; and not __fish_seen_subcommand_from status watch monitor mode fan cycle quiet balanced perf full oled display charge-limit rgb daemon completions session help" -f -a "charge-limit" -d 'Set battery charge limit threshold (0-100%)'
complete -c alatus -n "__fish_alatus_using_subcommand help; and not __fish_seen_subcommand_from status watch monitor mode fan cycle quiet balanced perf full oled display charge-limit rgb daemon completions session help" -f -a "rgb" -d 'Control keyboard RGB backlight and desktop accent color sync'
complete -c alatus -n "__fish_alatus_using_subcommand help; and not __fish_seen_subcommand_from status watch monitor mode fan cycle quiet balanced perf full oled display charge-limit rgb daemon completions session help" -f -a "daemon" -d 'Manage system hardware daemon and user desktop session background services'
complete -c alatus -n "__fish_alatus_using_subcommand help; and not __fish_seen_subcommand_from status watch monitor mode fan cycle quiet balanced perf full oled display charge-limit rgb daemon completions session help" -f -a "completions" -d 'Generate shell auto-completion scripts for Bash, Zsh, or Fish'
complete -c alatus -n "__fish_alatus_using_subcommand help; and not __fish_seen_subcommand_from status watch monitor mode fan cycle quiet balanced perf full oled display charge-limit rgb daemon completions session help" -f -a "session" -d 'Run desktop session integration agent (hidden/legacy compatibility)'
complete -c alatus -n "__fish_alatus_using_subcommand help; and not __fish_seen_subcommand_from status watch monitor mode fan cycle quiet balanced perf full oled display charge-limit rgb daemon completions session help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from mode" -f -a "get" -d 'Get current firmware mode'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from mode" -f -a "set" -d 'Set firmware mode (balanced, quiet, performance, full)'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from mode" -f -a "balanced" -d 'Switch to Balanced profile'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from mode" -f -a "quiet" -d 'Switch to Quiet profile'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from mode" -f -a "performance" -d 'Switch to Performance profile'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from mode" -f -a "full" -d 'Switch to Full speed profile'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from mode" -f -a "cycle" -d 'Cycle through profiles: Quiet -> Balanced -> Performance -> Full -> Quiet'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from mode" -f -a "auto" -d 'Query or configure auto-switching thermal profile on power changes'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from fan" -f -a "get" -d 'Get current fan profile'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from fan" -f -a "set" -d 'Set fan profile (balanced, quiet, performance, full)'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from fan" -f -a "balanced" -d 'Switch to Balanced profile'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from fan" -f -a "quiet" -d 'Switch to Quiet profile'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from fan" -f -a "performance" -d 'Switch to Performance profile'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from fan" -f -a "full" -d 'Switch to Full speed profile'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from fan" -f -a "cycle" -d 'Cycle through fan profiles: Quiet -> Balanced -> Performance -> Full -> Quiet'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from oled" -f -a "status" -d 'Show OLED care status, cumulative panel hours, cycle counts, and idle dimming state'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from oled" -f -a "dim" -d 'Toggle OLED idle dimming or specify target dimming percentage level'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from oled" -f -a "refresh" -d 'Trigger an immediate OLED pixel refresh conditioning cycle'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from display" -f -a "status" -d 'Show active panel connector, current refresh rate, resolution, and auto-refresh state'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from display" -f -a "rate" -d 'Switch refresh rate in Hz (e.g. 60, 120) or toggle auto power-matching (auto [on|off])'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from display" -f -a "dim" -d 'Scale flicker-free luminance level at compositor level (10-100%)'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from rgb" -f -a "status" -d 'Show current RGB status'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from rgb" -f -a "set-color" -d 'Set static RGB color via HEX (#RRGGBB, RRGGBB) or RGB values (R,G,B)'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from rgb" -f -a "set-brightness" -d 'Set RGB brightness level (0-100% or 0-3)'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from rgb" -f -a "off" -d 'Turn off keyboard RGB backlight'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from rgb" -f -a "on" -d 'Turn on keyboard RGB backlight'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from rgb" -f -a "sync" -d 'Toggle desktop accent color synchronization with keyboard backlighting'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from daemon" -f -a "session" -d 'Manage the desktop session background agent (alatus-session.service)'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from daemon" -f -a "system" -d 'Manage the system hardware daemon (alatusd.service)'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from daemon" -f -a "status" -d 'Show status of both background daemons'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from session" -f -a "status" -d 'Show active session agent status and configuration'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from session" -f -a "set" -d 'Dynamically configure session subsystems on the running agent'
complete -c alatus -n "__fish_alatus_using_subcommand help; and __fish_seen_subcommand_from session" -f -a "pixel-refresh" -d 'Trigger an immediate OLED pixel refresh conditioning cycle'
