// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Alatus Contributors

import { Palette } from "palette.slint";
import { Typography } from "typography.slint";

export { Palette, Typography }

export global Theme {
    // Spacing
    out property <length> spacing_xs: 4px;
    out property <length> spacing_sm: 8px;
    out property <length> spacing_md: 12px;
    out property <length> spacing_lg: 14px;
    out property <length> spacing_xl: 16px;
    out property <length> spacing_2xl: 24px;

    // Radii
    out property <length> radius_sm: 6px;
    out property <length> radius_md: 8px;
    out property <length> radius_lg: 10px;
    out property <length> radius_card: 14px;
    out property <length> radius_pill: 20px;
}

