[package]
name = "alatus-ipc"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
alatus-core = { path = "../alatus-core" }
serde = { version = "1.0", features = ["derive"] }
zbus = { version = "4.4", default-features = false, features = ["tokio"] }
zvariant = { version = "4.2", features = ["option-as-array"] }
